name: Docker Image CI2

on:
  workflow_dispatch:

env:
  IMAGE_NAME: gntouts/eltrak
  USER: gntouts
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.HUB_NAME }}
        DOCKER_PASSWORD: ${{secrets.HUB_PWD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo ${{ env.IMAGE_NAME }}
        echo ${{ env.USER }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s)
    - name: Docker Push
      run: docker push ${{ env.IMAGE_NAME }}
